version: '3'
services:
    postgresql:
        image: arm64v8/postgres:13.4
        restart: always
        env_file: ./.env
        ports: 
            - 3306:3306
        volumes:
            - ./docker/postgresql/data:/var/lib/postgresql/data
    
    nextcloud:
        image: arm64v8/nextcloud:20.0
        restart: always
        ports:
            - 80:80
        depends_on:
            - postgresql
        volumes:
            - ./docker/nextcloud/html:/var/www/html
        env_file: ./.env
